"""Investment stack canonical execution contracts v0.2."""

from __future__ import annotations

from investment_stack.contracts.calculation import (
    AssumptionKind,
    CalculationAssumption,
    CalculationRecord,
    CalculationStatus,
    DataAvailabilityStatus,
    ExecutionStatus,
    FormulaRequirement,
    GateDecision,
    GateState,
    InvestmentDecision,
    OutputKind,
    TypedOutput,
    ValidatedCalculation,
    validate_calculation_for_use,
)
from investment_stack.contracts.codec import (
    CONTRACT_VERSION,
    MAX_PAYLOAD_BYTES,
    compute_content_hash,
    compute_semantic_hash,
    decode_contract,
    decode_envelope,
    encode_contract,
    encode_envelope,
    format_decimal,
    parse_finite_decimal,
    parse_iso_date,
    parse_strict_bool,
    parse_strict_int,
    parse_strict_json,
    register_decoder,
    to_canonical_bytes,
    to_canonical_dict,
    to_canonical_json,
)
from investment_stack.contracts.context import (
    PinnedPersonalState,
    PublicAvailability,
    PublicAvailabilityKind,
    RunContext,
)
from investment_stack.contracts.errors import (
    AmbiguousSnapshotError,
    ContractError,
    ContractValidationError,
    CorruptedStorageError,
    DecimalValidationError,
    EvidenceNotFoundError,
    HistoryPreservationError,
    InputIntegrityError,
    KindValidationError,
    PayloadSizeExceededError,
    PointInTimeError,
    RevisionConflictError,
    SlotCoherenceError,
    TamperDetectionError,
    TimezoneValidationError,
    UnapprovedPolicyError,
)
from investment_stack.contracts.financial import (
    AccountingStandard,
    AdjustmentBasis,
    ConsolidationKind,
    FinancialFact,
    FinancialSet,
    PeriodType,
    ReportingFrequency,
    ScaleStatus,
    ShareBasis,
)
from investment_stack.contracts.institutional import (
    AmendmentType,
    Filing13F,
    Form13FKind,
    Holding13F,
    HoldingSet13F,
    NoticeStatus,
    PutCall,
    QuantityType,
)
from investment_stack.contracts.market import (
    AdjustmentMode,
    Bar,
    BarSet,
    MarketQuote,
    QuoteKind,
)
from investment_stack.contracts.slots import (
    BoundSlotInput,
    CalculationPurpose,
    CoverageDecision,
    DimensionKind,
    EligibilityDecision,
    EligibilityStatus,
    ExcludedCandidate,
    SelectedInputSet,
    SelectionRequest,
    SlotSpec,
)
from investment_stack.contracts.storage import (
    CONTRACT_STORAGE_KEY,
    MAX_PAYLOAD_SIZE_BYTES,
    build_canonical_binding_projection,
    deserialize_calculation_envelope,
    deserialize_snapshot_envelope,
    extract_contract_storage,
    serialize_calculation_envelope,
    serialize_snapshot_envelope,
    validate_contract_storage_ledger,
    validate_metadata_update_preservation,
)

__all__ = [
    # Codec & Version
    "CONTRACT_VERSION",
    "MAX_PAYLOAD_BYTES",
    "compute_content_hash",
    "compute_semantic_hash",
    "decode_contract",
    "decode_envelope",
    "encode_contract",
    "encode_envelope",
    "format_decimal",
    "parse_finite_decimal",
    "parse_iso_date",
    "parse_strict_bool",
    "parse_strict_int",
    "parse_strict_json",
    "register_decoder",
    "to_canonical_bytes",
    "to_canonical_dict",
    "to_canonical_json",
    # Errors
    "AmbiguousSnapshotError",
    "ContractError",
    "ContractValidationError",
    "CorruptedStorageError",
    "DecimalValidationError",
    "EvidenceNotFoundError",
    "HistoryPreservationError",
    "InputIntegrityError",
    "KindValidationError",
    "PayloadSizeExceededError",
    "PointInTimeError",
    "RevisionConflictError",
    "SlotCoherenceError",
    "TamperDetectionError",
    "TimezoneValidationError",
    "UnapprovedPolicyError",
    # Context
    "PinnedPersonalState",
    "PublicAvailability",
    "PublicAvailabilityKind",
    "RunContext",
    # Slots & Eligibility
    "BoundSlotInput",
    "CalculationPurpose",
    "CoverageDecision",
    "DimensionKind",
    "EligibilityDecision",
    "EligibilityStatus",
    "ExcludedCandidate",
    "SelectedInputSet",
    "SelectionRequest",
    "SlotSpec",
    # Financial
    "AccountingStandard",
    "AdjustmentBasis",
    "ConsolidationKind",
    "FinancialFact",
    "FinancialSet",
    "PeriodType",
    "ReportingFrequency",
    "ScaleStatus",
    "ShareBasis",
    # Market
    "AdjustmentMode",
    "Bar",
    "BarSet",
    "MarketQuote",
    "QuoteKind",
    # Institutional
    "AmendmentType",
    "Filing13F",
    "Form13FKind",
    "Holding13F",
    "HoldingSet13F",
    "NoticeStatus",
    "PutCall",
    "QuantityType",
    # Calculation
    "AssumptionKind",
    "CalculationAssumption",
    "CalculationRecord",
    "CalculationStatus",
    "DataAvailabilityStatus",
    "ExecutionStatus",
    "FormulaRequirement",
    "GateDecision",
    "GateState",
    "InvestmentDecision",
    "OutputKind",
    "TypedOutput",
    "ValidatedCalculation",
    "validate_calculation_for_use",
    # Storage
    "CONTRACT_STORAGE_KEY",
    "MAX_PAYLOAD_SIZE_BYTES",
    "build_canonical_binding_projection",
    "deserialize_calculation_envelope",
    "deserialize_snapshot_envelope",
    "extract_contract_storage",
    "serialize_calculation_envelope",
    "serialize_snapshot_envelope",
    "validate_contract_storage_ledger",
    "validate_metadata_update_preservation",
]
